package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/sqlc-dev/plugin-sdk-go/codegen"
	"github.com/sqlc-dev/plugin-sdk-go/plugin"
)

func main() {
	codegen.Run(generate)
}

type Options struct {
	TargetLang string `json:"target_lang"`
}

func generate(ctx context.Context, req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	f, err := os.OpenFile("./sqlc-plugin.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	if len(req.PluginOptions) == 0 {
		return nil, nil
	}

	var opts Options
	if err := json.Unmarshal([]byte(req.PluginOptions), &opts); err != nil {
		return nil, err
	}

	if opts.TargetLang != "ts" {
		return &plugin.GenerateResponse{}, nil
	}

	files := make(map[string][]string)

	for _, queries := range req.Queries {
		fmt.Fprintf(f, "Processing queries for file: %s\n", queries.Filename)
		fmt.Fprintf(f, "Name: %v\n", queries.Name)
		fmt.Fprintf(f, "Cmd: %v\n", queries.Cmd)
		for _, cols := range queries.Columns {
			fmt.Fprintf(f, "Column: %v\n", cols.Name)
		}
		for _, params := range queries.Params {
			fmt.Fprintf(f, "Param: %v\n", params.Column.Name)
		}

		if files[queries.Filename] == nil {
			files[queries.Filename] = []string{}
		}
		query := fmt.Sprintf("export const %s = `%s`\n", queries.Name, queries.Text)
		files[queries.Filename] = append(files[queries.Filename], query)
	}

	var filesGenerated []*plugin.File

	for filename := range files {
		contents := fmt.Sprintf("// This file is generated by sqlc plugin-gen-ts. DO NOT EDIT.\n\n%s", strings.Join(files[filename], "\n"))
		filesGenerated = append(filesGenerated, &plugin.File{
			Name:     filename + ".ts",
			Contents: []byte(contents),
		})
		fmt.Fprintf(f, "Generated file: %s\n", filename+".ts")
	}

	return &plugin.GenerateResponse{
		Files: filesGenerated,
	}, nil
}
