package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/sqlc-dev/plugin-sdk-go/codegen"
	"github.com/sqlc-dev/plugin-sdk-go/plugin"
)

func main() {
	codegen.Run(generate)
}

type Options struct {
	TargetLang string `json:"target_lang"`
}

func generate(ctx context.Context, req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	// f, err := os.OpenFile("./sqlc-plugin.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	// if err != nil {
	// 	return nil, err
	// }
	// defer f.Close()

	if len(req.PluginOptions) == 0 {
		return nil, nil
	}

	var opts Options
	if err := json.Unmarshal([]byte(req.PluginOptions), &opts); err != nil {
		return nil, err
	}

	if opts.TargetLang != "ts" {
		return &plugin.GenerateResponse{}, nil
	}

	files := make(map[string][]string)

	for _, queries := range req.Queries {
		if files[queries.Filename] == nil {
			files[queries.Filename] = []string{}
		}
		query := fmt.Sprintf("export const %s = `%s`\n", queries.Name, queries.Text)
		files[queries.Filename] = append(files[queries.Filename], query)
	}

	var filesGenerated []*plugin.File

	for filename := range files {
		contents := fmt.Sprintf("// This file is generated by sqlc plugin-gen-ts. DO NOT EDIT.\n\n%s", strings.Join(files[filename], "\n"))
		filesGenerated = append(filesGenerated, &plugin.File{
			Name:     filename + ".ts",
			Contents: []byte(contents),
		})
	}

	return &plugin.GenerateResponse{
		Files: filesGenerated,
	}, nil
}
