name: release
on:
  push:
    tags:
      - '*-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.26
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SQLC_RELEASE }}
          fetch-depth: 0

      - name: build
        run: |
          cd src/pluging-insert-checker
          GOOS=wasip1 GOARCH=wasm go build -buildvcs=false -o pluging-insert-checker.wasm

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Automated release for ${{ github.ref_name }}"
          files: |
            src/pluging-insert-checker/pluging-insert-checker.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.SQLC_RELEASE }}