name: tag

on:
  push:
    branches: [main]

jobs:
  changes:
    uses: ./.github/workflows/changed-projects.yml

  tag:
    needs: changes
    if: needs.changes.outputs.projects != '[]'
    runs-on: ubuntu-latest
    container: golang:1.26

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.changes.outputs.projects) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SQLC_RELEASE }}
          fetch-depth: 0

      - name: Build ${{ matrix.project }}
        run: |
          cd "src/${{ matrix.project }}"
          go build -buildvcs=false -o "${{ matrix.project }}"

      - name: Tag ${{ matrix.project }}
        run: |
          git config --global --add safe.directory /__w/sqlc/sqlc
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch --tags
          ./tag.sh "${{ matrix.project }}"
          git push origin --tags